apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blue-green-canary
  name: canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-green-canary
  template:
    metadata:
      labels:
        app: blue-green-canary
        group: bgc
        version: canary
      annotations:
        sidecar.istio.io/inject: "true"        
    spec:
      containers:
      - name: canary
        image: docker.io/burrsutter/blue-green-canary:canary
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
          requests: 
            memory: "50Mi" 
            cpu: "100m" 
          limits:
            memory: "120Mi"
            cpu: "250m" 
        livenessProbe:
          httpGet:
              port: 8080
              path: /api
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            port: 8080
            path: /api
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 2

