apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: bgc-git-source
spec:
  type: git
  params:
    - name: url
      value: https://github.com/redhat-developer-demos/blue-green-canary
    - name: revision
      value: master
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: bgc-image
spec:
  type: image
  params:
    - name: url
      value: "image-registry.openshift-image-registry.svc:5000/tutorial/blue-green-canary"
